WebApp/Controllers/IssueController.cs
using BLL.DTO.IssueDTO;
using BLL.DTO.UserDTO;
using BLL.Repositories.Issue;
using BLL.Repositories.Pos;
using Newtonsoft.Json;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebApp.Helpers;
using BLL.DTO.IssueDTO.IssueValidation;
using FluentValidation.Results;


namespace WebApp.Controllers
{
	public class IssueController : Controller
	{
		private readonly IIssueRepository issueRepository;
		private readonly IPosRepository posRepository;


		public IssueController(IIssueRepository issueRepository, IPosRepository posRepository)
		{
			this.issueRepository = issueRepository;
			this.posRepository = posRepository;
		}

		[HttpGet]
		public ActionResult BrowsePos()
		{
			return View();
		}

		[HttpGet]
		public ActionResult CreateIssue(int id)
		{
			var posModel = posRepository.GetPosById(id);

			ViewBag.IssueType = issueRepository.GetAllIssuesType();
			ViewBag.Priority = issueRepository.GetPriority();
			ViewBag.Status = issueRepository.GetStatuses();

			var model = new AddIssuesDTO
			{
				IdPos = id,
				PosName = posModel.Name,
				PosTelephone = posModel.Telephone,
				PosCellPhone = posModel.CellPhone,
				PosAddress = posModel.Address
			};

			return View(model);
		}

		[HttpPost]
		public ActionResult CreateIssue(AddIssuesDTO issueModel)
		{
			IssueValidation issueValidation = new IssueValidation(issueRepository);
			ValidationResult result = issueValidation.Validate(issueModel);

			if (ModelState.IsValid)
			{
				HttpCookie authCookie = Request.Cookies[FormsAuthentication.FormsCookieName];
				FormsAuthenticationTicket authTicket = FormsAuthentication.Decrypt(authCookie.Value);
				var user = JsonConvert.DeserializeObject<GetUserDTO>(authTicket.UserData);

				issueModel.IdUserCreated = user.Id;
				issueModel.IdUserType = user.UserTypeId;

				issueRepository.AddIssue(issueModel);
				return RedirectToAction("BrowseIssue");
			}
			else
			{
				foreach (var failure in result.Errors)
				{
					ModelState.AddModelError(failure.PropertyName, failure.ErrorMessage);
				}
			}


			ViewBag.IssueType = issueRepository.GetAllIssuesType();
			return View();
		}

		[HttpGet]
		public ActionResult BrowseIssue()
		{

			return View();

		}

		[HttpGet]
		public JsonResult QueryPos()
		{
			var criteria = Request.GetPaginatingCriteria();

			var pos = posRepository.QueryPos(criteria);

			var jsonData = new
			{
				draw = Request.QueryString["draw"],
				recordsTotal = pos.Total,
				recordsFiltered = pos.TotalFiltered,
				data = pos.PossDTO

			};

			return Json(jsonData, JsonRequestBehavior.AllowGet);
		}

		public JsonResult QueryIssue()
		{
			var criteria = Request.GetPaginatingCriteria();

			var issue = issueRepository.QueryIssue(criteria);

			var jsonData = new
			{
				draw = Request.QueryString["draw"],
				recordsTotal = issue.Total,
				recordsFiltered = issue.TotalFiltered,
				data = issue.IssueDTO

			};

			return Json(jsonData, JsonRequestBehavior.AllowGet);
		}

		public JsonResult QueryLogs(int id )
		{
			var criteria = Request.GetPaginatingCriteria();

			var log = issueRepository.QueryLogs(criteria);

			var filtredData = log.Logs.Where(x => x.IssueId == id).ToList();
			var jsonData = new
			{
				draw = Request.QueryString["draw"],
				recordsTotal = log.Total,
				recordsFiltered = filtredData.Count,
				data = filtredData


			};

			return Json(jsonData, JsonRequestBehavior.AllowGet);
		}

		[HttpPost]
		public ActionResult EditIssue(UpdateIssuesDTO updateIssues)
		{
			var issueTypes = issueRepository.GetAllIssuesType();
			ViewBag.IssueType = issueTypes.Where(x => x.IssueLevel == 1).ToList();
			ViewBag.SubType = issueTypes.Where(x => x.IssueLevel == 2).ToList();
			ViewBag.ProblemType = issueTypes.Where(x => x.IssueLevel == 3).ToList();
			ViewBag.Priority = issueRepository.GetPriority();
			ViewBag.Status = issueRepository.GetStatuses();
			ViewBag.UserType = issueRepository.GetUserType();

			if (ModelState.IsValid)
			{
				issueRepository.UpdateIssue(updateIssues);
				return RedirectToAction("BrowseIssue");
			}
			return View("_EditIssuePartialView");
		}

		[HttpGet]
		public ActionResult EditIssuePartialView(int issueId)
		{
			var issueTypes = issueRepository.GetAllIssuesType();
			ViewBag.IssueType = issueTypes.Where(x => x.IssueLevel == 1).ToList();
			ViewBag.SubType = issueTypes.Where(x => x.IssueLevel == 2).ToList();
			ViewBag.ProblemType = issueTypes.Where(x => x.IssueLevel == 3).ToList();
			ViewBag.Priority = issueRepository.GetPriority();
			ViewBag.Status = issueRepository.GetStatuses();
			ViewBag.UserType = issueRepository.GetUserType();

			var issue = issueRepository.GetIssueById(issueId);

			var updateIssueDTO = new UpdateIssuesDTO
			{
				Id = issue.Id,
				IdPos = issue.IdPos,
				PosName = issue.PosName,
				IdType = issue.IdType,
				IdSubType = issue.IdSubType,
				IdProblem = issue.IdProblem,
				IdStatus = issue.IdStatus,
				PriorityId = issue.PriorityId,
				Solution = issue.Solution,
				Memo = issue.Memo,
				IdUserCreated = issue.IdUserCreated,
				IdUserType = issue.IdUserType,
				ProblemDescription = issue.ProblemDescription,
				PosTelephone = issue.PosTelephone,
				PosCellPhone = issue.PosCellPhone,
				PosAddress = issue.PosAddress,
			};

			return View("_EditIssuePartialView", updateIssueDTO);
		}

		[HttpGet]
		public ActionResult DetailsIssuePartialView(int issueId)
		{
			var issueTypes = issueRepository.GetAllIssuesType();
			ViewBag.IssueType = issueTypes.Where(x => x.IssueLevel == 1).ToList();
			ViewBag.SubType = issueTypes.Where(x => x.IssueLevel == 2).ToList();
			ViewBag.ProblemType = issueTypes.Where(x => x.IssueLevel == 3).ToList();
			ViewBag.Priority = issueRepository.GetPriority();
			ViewBag.Status = issueRepository.GetStatuses();
			ViewBag.UserType = issueRepository.GetUserType();

			var issue = issueRepository.GetIssueById(issueId);

			return View("_DetailsIssuePartialView", issue);
		}
	}
}

WebApp/Controllers/PosController.cs
using BLL.DTO.PosDTO;
using BLL.Repositories.Pos;
using System.Web.Mvc;
using WebApp.Helpers;
using FluentValidation;
using BBL.DTO.PosDTO.PosValidation;
using FluentValidation.Results;

namespace WebApp.Controllers
{
	[Authorize]
	public class PosController : Controller
	{
		private readonly IPosRepository posRepository;
		private readonly PosValidation validation;

		public PosController(IPosRepository posRepository, PosValidation validation)
		{
			this.posRepository = posRepository;
			this.validation = validation;	

		}

		// GET: Pos
		[HttpGet]
		public ActionResult BrowsePos()
		{
			return View();
		}


		[HttpGet]
		public JsonResult QueryPos()
		{
			var criteria = Request.GetPaginatingCriteria();

			var pos = posRepository.QueryPos(criteria);

			var jsonData = new
			{
				draw = Request.QueryString["draw"],
				recordsTotal = pos.Total,
				recordsFiltered = pos.TotalFiltered,
				data = pos.PossDTO

			};

			return Json(jsonData, JsonRequestBehavior.AllowGet);
		}


		[HttpGet]
		public ActionResult AddPosPartialView()
		{

			ViewBag.City = posRepository.GetAllCitites();
			ViewBag.ConType = posRepository.GetAllConnectionType();

			return PartialView("_AddPosPartialView");
		}


		//[HttpPost]
		//public ActionResult CreatePos(AddPOSDTO pos)
		//{
		//	PosValidation posValidator = new PosValidation(posRepository);

		//	ValidationResult result = posValidator.Validate(pos);

		//	if (ModelState.IsValid)
		//	{
		//              ViewBag.City = posRepository.GetAllCitites();
		//              ViewBag.ConType = posRepository.GetAllConnectionType();
		//              posRepository.AddPos(pos);
		//		return PartialView("_AddPosPartialView", pos);
		//	}
		//	else
		//	{
		//		foreach (var failure in result.Errors)
		//		{
		//			ModelState.AddModelError(failure.PropertyName, failure.ErrorMessage);
		//		}
		//	}


		//          return PartialView("_AddPosPartialView", pos);
		//}

		[HttpPost]
		public ActionResult CreatePos(AddPOSDTO posModel)
		{
			PosValidation posValidator = new PosValidation(posRepository);

			ValidationResult result = posValidator.Validate(posModel);

			if (ModelState.IsValid)
			{
				ViewBag.City = posRepository.GetAllCitites();
				ViewBag.ConType = posRepository.GetAllConnectionType();
				posRepository.AddPos(posModel);
				return PartialView("_AddPosPartialView", posModel);
            }
			else
			{
				foreach (var failure in result.Errors)
				{
					ModelState.AddModelError(failure.PropertyName, failure.ErrorMessage);
				}
			}


			
            return PartialView("_AddPosPartialView", posModel);
        }

            [HttpPost]
		public ActionResult EditPos(UpdatePosDTO updatePos)
		{
			ViewBag.City = posRepository.GetAllCitites();
			ViewBag.ConType = posRepository.GetAllConnectionType();

			if (ModelState.IsValid)
			{
				posRepository.UpdatePos(updatePos);
				return PartialView("_EditPosPartialView", updatePos);

			}
			return PartialView("_EditPosPartialView", updatePos);
		}

		[HttpGet]
		public ActionResult EditPosPartialView(int posId)
		{
			var pos = posRepository.GetPosById(posId);

			ViewBag.City = posRepository.GetAllCitites();
			ViewBag.ConType = posRepository.GetAllConnectionType();

			var updatePosDTO = new UpdatePosDTO
			{
				Id = posId,
				Name = pos.Name,
				Telephone = pos.Telephone,
				CellPhone = pos.CellPhone,
				City_Id = pos.City_Id,
				CityName = pos.CityName,
				Brand = pos.Brand,
				Model = pos.Model,
				ConnType_Id = pos.ConnType_Id,
				ConnectionType = pos.ConnectionType,
				Address = pos.Address,
				IssuesId = pos.IssuesId,
				MorningOperning = pos.MorningOperning,
				MorningClosing = pos.MorningClosing,
				AfternoonOpening = pos.AfternoonOpening,
				AfternonClosing = pos.AfternonClosing,
				SelectedDays = pos.SelectedDays,
				Status = pos.Status,
			};

			return PartialView("_EditPosPartialView", updatePosDTO);
		}

		[HttpGet]
		public ActionResult DetailsPosPartialView(int posId)
		{

			var pos = posRepository.GetPosById(posId);
			return PartialView("_DetailsPosPartialView", pos);
		}
	}
}

WebApp/Controllers/UserController.cs
using BBL.DTO.PosDTO.PosValidation;
using BBL.DTO.UserDTO.UserValidation;
using BLL.DTO.UserDTO;
using BLL.Repositories.User;
using FluentValidation.Results;
using System.Web.Mvc;
using WebApp.Helpers;

namespace WebApp.Controllers
{
	[Authorize]
	public class UserController : Controller
	{
		private readonly IUserRepository userRepository;
		private readonly AddUserValidation validation;

		public UserController(IUserRepository userRepository, AddUserValidation validation)
		{

			this.userRepository = userRepository;
			this.validation = validation;
		}

		// GET: User
		[HttpGet]
		public ActionResult Browse()
		{
			return View();
		}

		[HttpGet]
		public JsonResult QueryUsers()
		{
			var criteria = Request.GetPaginatingCriteria();

			var users = userRepository.QueryUsers(criteria);

			var jsonData = new
			{
				draw = Request.QueryString["draw"],
				recordsTotal = users.Total,
				recordsFiltered = users.TotalFiltered,
				data = users.UserDTO
			};

			return Json(jsonData, JsonRequestBehavior.AllowGet);
		}


		[HttpGet]
		public ActionResult CreateUserPartialView()
		{
			ViewBag.UserTypes = userRepository.GetAllUsersType();
            return PartialView("_CreateUserPartialView");
        }

		[HttpPost]
		public ActionResult CreateUser(AddUserDTO model)
		{
			AddUserValidation userValidation = new AddUserValidation(userRepository);
			ValidationResult result = userValidation.Validate(model);

			if (ModelState.IsValid)
			{
                ViewBag.UserTypes = userRepository.GetAllUsersType();
                userRepository.AddUser(model);
                return PartialView("_CreateUserPartialView",model);
            }
			else 
			{
				foreach(var failure in result.Errors)
				{
					ModelState.AddModelError(failure.PropertyName, failure.ErrorMessage);
				}
			}
			
			ViewBag.UserTypes = userRepository.GetAllUsersType();
            return PartialView("_CreateUserPartialView",model);

        }

		[HttpPost]
		public ActionResult EditUser(UpdateUserDTO user)
		{
			ViewBag.UserTypes = userRepository.GetAllUsersType();

			if (ModelState.IsValid)
			{
				userRepository.UpdateUser(user);
				return PartialView("_EditUserPartialView", user);
			}

			return PartialView("_EditUserPartialView", user);
		}

		[HttpGet]
		public ActionResult EditUserPartialView(int userId)
		{
			var getUserDTO = userRepository.GetUserById(userId);

			ViewBag.UserTypes = userRepository.GetAllUsersType();

			var updateUserDTO = new UpdateUserDTO
			{
				Id = userId,
				Name = getUserDTO.Name,
				Email = getUserDTO.Email,
				Login = getUserDTO.Login,
				Telephone = getUserDTO.Telephone,
				UserTypeId = getUserDTO.UserTypeId,
			};

			return PartialView("_EditUserPartialView", updateUserDTO);
		}

		[HttpGet]
		public ActionResult DetailsUserPartialView(int userId)
		{
			var getUserDTO = userRepository.GetUserById(userId);

			return PartialView("_DetailsUserPartialView", getUserDTO);
		}
	}
}

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <title>Libra!</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/font-awesome/css/font-awesome.css" rel="stylesheet">
    <link href="~/Content/datatables.min.css" rel="stylesheet">
    <link href="~/Content/custom.min.css" rel="stylesheet">
    <link href="~/Content/jquery.dataTables.min.css" rel="stylesheet">
    <link href="~/Content/Style.css" rel="stylesheet">



<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <header>
                <div class="col-md-3 left_col menu_fixed">
                    <div class="left_col scroll-view">
                        <div class="navbar nav_title" style="border: 0;">
                            <a href="index.html" class="site_title">
                                <i class="fa fa-bank"></i> <span>Libra Dashboard!</span>
                            </a>
                        </div>
                        <div class="clearfix"></div>
                        <div class="profile clearfix">
                            <div class="profile_pic">
                            </div>
                            <div class="profile_info">
                                <h1>Welcome</h1>
                               
                                <h2>@User.Identity.Name </h2>
                            </div>
                        </div>
                        <br />

                        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                            <div class="menu_section">

                                <ul class="nav side-menu">
                                    <li>
                                        <a href="@Url.Action("Index", "Home")" class="nav-link">
                                            <i class="fa fa-tachometer" aria-hidden="true"></i> Dashboard
                                        </a>
                                    </li>

                                    <li>
                                        <a href="#"><i class="fa fa-credit-card"></i> POS <span class="fa fa-chevron-down"></span></a>
                                        <ul class="nav child_menu">
                                            @*<li>
                                                    @Html.ActionLink("Add POS", "CreatePos", "Pos", null, new { @class = "nav-link" })
                                                </li>*@
                                            <li> @Html.ActionLink("Browse POS", "BrowsePos", "Pos", null, new { @class = "nav-link" }) </li>
                                        </ul>
                                    </li>
                                    <li>
                                        <a><i class="fa fa-wrench"></i> Issues <span class="fa fa-chevron-down"></span></a>
                                        <ul class="nav child_menu">
                                            <li>
                                                @Html.ActionLink("Add Issue", "BrowsePos", "Issue", null, new { @class = "nav-link" })
                                            <li>
                                                @Html.ActionLink("Browse Issue", "BrowseIssue", "Issue", null, new { @class = "nav-link" })
                                            </li>

                                        </ul>
                                    </li>
                                    <li>
                                        @if (User.IsInRole("admin"))
                                        {
                                            <a><i class="fa fa-user"></i> Users<span class="fa fa-chevron-down"></span></a>
                                            <ul class="nav child_menu">
                                                @*<li>
                                                        @Html.ActionLink("Add User", "CreateUser", "User", null, new { @class = "nav-link" })
                                                    </li>*@
                                                <li>
                                                    @Html.ActionLink("Browse User", "Browse", "User", null, new { @class = "nav-link" })
                                                </li>
                                            </ul>
                                         }
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="top_nav">
                    <div class="nav_menu">
                        <div class="nav toggle">
                            <a id="menu_toggle">
                                <i class="fa fa-bars"></i>
                            </a>
                        </div>
                        <nav class="nav navbar-na pull-right">
                            <ul class=" navbar-right">
                                <li class="nav-item dropdown open">
                                    <a href="javascript:;" class="user-profile dropdown-toggle" aria-haspopup="true" id="navbarDropdown" data-toggle="dropdown" aria-expanded="false">

                                        @User.Identity.Name
                                    </a>
                                    <span style="margin-left :10px;"></span>
                                    @Html.ActionLink("Log out", "LogOff", "Authorization", null, new { @class = "nav-link" })
                                    <a><i class="fa fa-sign-out"></i></a>
                                </li>

                            </ul>
                        </nav>
                    </div>
                </div>
            </header>
            <div class="right_col">
                <main role="main">
                    @RenderBody()
                </main>
            </div>

        </div>
    </div>


    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <script src="~/Scripts/jquery-3.6.0.min.js"></script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/custom")
    @RenderSection("scripts", required: false)
</body>
</html>